version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wealthsearch
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wealthsearch"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - db_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_KEEP_ALIVE: "24h"
    command: >
      /bin/sh -lc "
        ollama serve &
        until nc -z localhost 11434; do sleep 1; done;
        ollama pull ${OLLAMA_TEXT_MODEL:-llama3.1} || true;
        wait -n
      "
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:11434/api/tags >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wealthsearch
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_TEXT_MODEL: ${OLLAMA_TEXT_MODEL:-llama3.1}
    ports:
      - "8080:8080"

volumes:
  db_data:
  ollama_data:

