version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      # чтобы не тянул большие модели случайно, держим всё локально
      OLLAMA_KEEP_ALIVE: "24h"
    command: >
      /bin/sh -lc "
        ollama serve &
        # ждём порт
        until nc -z localhost 11434; do sleep 1; done;
        # подтягиваем нужные модели
        ollama pull ${OLLAMA_TEXT_MODEL} || true;
        # эмбеддинги тебе тут не обязательны, но вдруг
        # ollama pull nomic-embed-text || true;
        wait -n
      "
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:11434/api/tags >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_TEXT_MODEL: ${OLLAMA_TEXT_MODEL}
      # при желании: LOG_LEVEL=INFO
    ports:
      - "8080:8080"