spring:
  application:
    name: wealth-search-engine
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wealthsearch}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  flyway:
    locations: classpath:db/migration
  jooq:
    sql-dialect: POSTGRES
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_TEXT_MODEL:gemma2:2b}
        request:
          stream: false
          format: json
          options:
            temperature: 0.3
            top-p: 0.9
            top-k: 40
            repeat-penalty: 1.2
            seed: 42
            num-predict: 200
      embedding:
        model: ${OLLAMA_EMBED_MODEL:gemma2:2b}

logging:
  level:
    com.wealthsearch: INFO
    org.jooq.tools.LoggerListener: WARN

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

semantic-search:
  prompts:
    synonym-path: classpath:prompts/synonym-query-expand.txt
document-summary:
  prompts:
    short-summary: classpath:prompts/doc-summary.txt

ollama:
  client:
    connect-timeout: 30s
    read-timeout: 30s
    response-timeout: 30s
    write-timeout: 30s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  writer-with-default-pretty-printer: true

resilience4j:
  circuitbreaker:
    instances:
      ollama:
        slidingWindowSize: 10
        waitDurationInOpenState: 10s