spring:
  application:
    name: wealth-search-engine
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wealthsearch}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:wealth}
    password: ${SPRING_DATASOURCE_PASSWORD:wealth}
  flyway:
    locations: classpath:db/migration
  jooq:
    sql-dialect: POSTGRES

logging:
  level:
    com.wealthsearch: INFO
    org.jooq.tools.LoggerListener: WARN

server:
  port: 8080
